name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI_CXXFLAGS: -O2 -Wall -Wextra -Wshadow=local -Werror -pedantic
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: |
          libavcodec-dev
          libavformat-dev
          libavutil-dev
          libpng-dev
          libquazip5-dev
          libsdl2-dev
          libsdl2-image-dev
          libswresample-dev
          libswscale-dev
          qtbase5-dev
          qttools5-dev-tools
        version: 1.0
    - name: make
      run: |
        mkdir build
        cd build
        qmake .. PREFIX="/usr/local" QMAKE_CXXFLAGS="${CI_CXXFLAGS}"
        make -j4
